---

- hosts: swarm
  tasks:
    - name: Create bind mounts for gitlab
      file: >
        path="{{item}}"
      
        state=directory
        recurse=yes
      with_items: 
        - '/srv/gitlab/config'
        - '/srv/gitlab/logs'
        - '/srv/gitlab/data'
        
    - name: gitlab.rb
      copy: 
        dest: /tmp/gitlab.rb
        content: |
          external_url 'http://gitlab-web.swarm.main.local/'
          gitlab_rails['initial_root_password'] = qwerty
    # - name: gitlab_root_password
    #   copy:
    #     dest: /tmp/root_password.txt
    #     content: "qwerty"


- hosts: manager[0]

  tasks:

    # - name: deploy 'stack2' from yaml
    #   docker_stack:
    #     state: present
    #     name: stack2
    #     compose_yaml: |
    #         version: '3'
    #         services:
    #             web:
    #                 image: nginx
    #                 networks:
    #                   - net
    #                   - traefik-net
    #                 deploy:
    #                   replicas: 3
    #                   labels:
    #                     - "traefik.docker.network=traefik-net"
    #                     - "traefik.port=80"
    #         networks:
    #           net:
    #             driver: overlay
    #           traefik-net:
    #             external:
    #               name: traefik-net

      
      

    - name: deploy 'gitlab' from yaml
      docker_stack:
        with_registry_auth: true
        state: absent
        name: gitlab
        compose_yaml: |
            version: '3.6'
            services:
                web:
                  image: 'gitlab/gitlab-ce:latest'
                  networks:
                    - net
                    - traefik-net
                  deploy:
                    replicas: 1
                    labels:
                      - "traefik.docker.network=traefik-net"
                      - "traefik.port=80"
                    placement:
                      constraints:
                        - node.hostname == swarm2.local


                  volumes:
                    - '/srv/gitlab/config:/etc/gitlab'
                    - '/srv/gitlab/logs:/var/log/gitlab'
                    - '/srv/gitlab/data:/var/opt/gitlab'
                  environment:
                    GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
                  configs:
                    - source: gitlab
                      target: /omnibus_config.rb

                runner:
                  image: 'gitlab/gitlab-runner:alpine'
                  deploy:
                    mode: replicated
                    replicas: 3

            networks:
              net:
                driver: overlay
              traefik-net:
                external:
                  name: traefik-net
            configs:
              gitlab:
                file: ./gitlab.rb

